# Generated by Django 3.2.5 on 2021-07-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=100)),
                ('id_mom', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='', max_length=100)),
                ('customer_address', models.CharField(default='', max_length=500)),
                ('customer_phone', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0, null=True)),
                ('customer_id', models.IntegerField(default=0, null=True)),
                ('fee_and_ship', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=10)),
                ('product_name', models.CharField(default='', max_length=200)),
                ('product_spice', models.IntegerField(default=0, null=True)),
                ('product_desception', models.CharField(default='', max_length=2000)),
                ('product_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
